package Hospital;


import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author geros
 */
public class Hospital extends javax.swing.JFrame {
    private JFrame frame;
    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnPrescription = new javax.swing.JButton();
        jBtnLogin = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jComboTablet = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPatientAddres = new javax.swing.JTextField();
        jRef = new javax.swing.JTextField();
        jDoze = new javax.swing.JTextField();
        jNumTablets = new javax.swing.JTextField();
        jLOT = new javax.swing.JTextField();
        jIssuedDate = new javax.swing.JTextField();
        jExpDate = new javax.swing.JTextField();
        jDailyDose = new javax.swing.JTextField();
        jSideEffect = new javax.swing.JTextField();
        jFurInfo = new javax.swing.JTextField();
        jStorageAdvice = new javax.swing.JTextField();
        jMachODrive = new javax.swing.JTextField();
        jHowto = new javax.swing.JTextField();
        jPatientID = new javax.swing.JTextField();
        jNHSnum = new javax.swing.JTextField();
        jPatientName = new javax.swing.JTextField();
        jBirth = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(255, 51, 102));
        exit.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.setBorderPainted(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 30));

        jBtnUpdate.setBackground(new java.awt.Color(0, 255, 51));
        jBtnUpdate.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jBtnUpdate.setText("Update");
        jBtnUpdate.setBorderPainted(false);
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jBtnDelete.setBackground(new java.awt.Color(255, 51, 51));
        jBtnDelete.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jBtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDelete.setText("Delete");
        jBtnDelete.setBorderPainted(false);
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jBtnReset.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 30));

        jBtnPrescription.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jBtnPrescription.setText("Prescription");
        jBtnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrescriptionActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 30));

        jBtnLogin.setBackground(new java.awt.Color(0, 255, 51));
        jBtnLogin.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jBtnLogin.setText("Login");
        jBtnLogin.setBorderPainted(false);
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, 30));

        jButton10.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jButton10.setText("Print");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1390, 50));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel2.setText("Patient Prescription");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 920, 60));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel1.setText("Hospital Managment System");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1380, 90));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPrescription.setColumns(20);
        jtxtPrescription.setRows(5);
        jScrollPane2.setViewportView(jtxtPrescription);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 460));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 460, 480));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel3.setText("Issued Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jComboTablet.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jComboTablet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Prescription", "Parecetamol", "Dopamina", "Morfin", "Ibuprofeno" }));
        jComboTablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTabletActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 160, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel4.setText("LOT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel5.setText("Expired Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel6.setText("Patient's Address:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel7.setText("Reference n°:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel8.setText("Name Of  The Tablet");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel9.setText("Dosis (Mg):");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel10.setText("Numbers of tablets:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel11.setText("Storage Advice:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel12.setText("Further Information:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel13.setText("Drivin or Using Machines:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel14.setText("How To Use Medication:");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 110, 40));

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel15.setText("NHS Number");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        jLabel16.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel16.setText("Patient ID:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel17.setText("Patient Name:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        jLabel18.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel18.setText("Date Of Birth:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        jLabel19.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel19.setText("Daily Dose");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel20.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel20.setText("Side Effects:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jPatientAddres.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jPatientAddres, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 280, -1));

        jRef.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 280, -1));

        jDoze.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jDoze, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 280, -1));

        jNumTablets.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jNumTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 280, -1));

        jLOT.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jLOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 280, -1));

        jIssuedDate.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 280, -1));

        jExpDate.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 280, -1));

        jDailyDose.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 280, -1));

        jSideEffect.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jSideEffect, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 280, -1));

        jFurInfo.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jFurInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 280, -1));

        jStorageAdvice.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 280, -1));

        jMachODrive.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jMachODrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 250, -1));

        jHowto.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jHowto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 270, 50));

        jPatientID.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 280, -1));

        jNHSnum.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jNHSnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 280, -1));

        jPatientName.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 280, -1));

        jBirth.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        getContentPane().add(jBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 280, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of the Tablet", "Reference N°", "Dosis (Mg)", "Numbers Of Tablets", "LOT", "Issued Date", "Experid Date", "Dailiy Dose", "Side Effects", "Further Information", "Storage Advice", "Drive Or Machine", "How  To Use", "Client ID", "NHS Number ", "Pacient Name", "Date Of Birth", "Patient's address"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1390, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         frame = new JFrame();
         
         if(JOptionPane.showConfirmDialog(frame, "Do you want to exit?", 
                 "Hospital Managment System", JOptionPane.YES_NO_OPTION) ==
                 JOptionPane.YES_NO_OPTION){
             System.exit(0);
         }
    }//GEN-LAST:event_exitActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try{
            jtxtPrescription.print();
        }catch(PrinterException e){
            Logger.getLogger(Hospital.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboTabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTabletActionPerformed
        // TODO add your handling code here:
        if(jComboTablet.getSelectedItem().equals("Ibuprofeno")){
            jRef.setText("Ibupro 2356");
            jDoze.setText("50");
            jNumTablets.setName("3");
            jLOT.setText("124578");
            jIssuedDate.setText("15/09/18");
            jDailyDose.setText("3");
            jExpDate.setText("10/10/2019");
            
            jSideEffect.setText("Fatigue");
            jFurInfo.setText("No make Excersice");
            jStorageAdvice.setText("No Advice");
            jMachODrive.setText("NO");
            jHowto.setText("Drink with Water, No alcohol.");
            
        } else if(jComboTablet.getSelectedItem().equals("Morfin")){
            jRef.setText("Morfin 56");
            jDoze.setText("10");
            jNumTablets.setName("2");
            jLOT.setText("852178");
            jIssuedDate.setText("15/04/18");
            jDailyDose.setText("1");
            jExpDate.setText("10/10/2019");
            
            jSideEffect.setText("Fatigue, Sleepeness");
            jFurInfo.setText("No Combine with Other Drugs");
            jStorageAdvice.setText("Under 30 Celsius");
            jMachODrive.setText("YES");
            jHowto.setText("Inyect In the arm");
            
        } else if(jComboTablet.getSelectedItem().equals("Parecetamol")){
            jRef.setText("Para 7845");
            jDoze.setText("50");
            jNumTablets.setName("5");
            jLOT.setText("426985");
            jIssuedDate.setText("15/09/17");
            jDailyDose.setText("2");
            jExpDate.setText("10/10/2019");
            
            jSideEffect.setText("Fatigue");
            jFurInfo.setText("");
            jStorageAdvice.setText("No Advice");
            jMachODrive.setText("NO");
            jHowto.setText("Drink with Water, No alcohol.");
            
        } else if(jComboTablet.getSelectedItem().equals("Dopamina")){
            jRef.setText("Dona 56");
            jDoze.setText("40");
            jNumTablets.setName("3");
            jLOT.setText("124796");
            jIssuedDate.setText("25/04/18");
            jDailyDose.setText("1");
            jExpDate.setText("10/10/2019");
            
            jSideEffect.setText("Fatigue");
            jFurInfo.setText("");
            jStorageAdvice.setText("In Cold Temperature");
            jMachODrive.setText("YES");
            jHowto.setText("Drink with Water, No alcohol.");  
        } else {
            jRef.setText("");
            jDoze.setText("");
            jNumTablets.setName("");
            jLOT.setText("");
            jIssuedDate.setText("");
            jDailyDose.setText("");
            jExpDate.setText("");
            
            jSideEffect.setText("");
            jFurInfo.setText("");
            jStorageAdvice.setText("");
            jMachODrive.setText("");
            jHowto.setText("");
        }
    }//GEN-LAST:event_jComboTabletActionPerformed

    private void jBtnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrescriptionActionPerformed
        // TODO add your handling code here: 
        String Q1 = jRef.getText();
        String Q2 = jDoze.getText();
        String Q3 = jLOT.getText();
        String Q4 = jNumTablets.getText();
        String Q5 = jDailyDose.getText();
        String Q6 = jSideEffect.getText();
        String Q7 = jFurInfo.getText();
        String Q8 = jHowto.getText();
        String Q9 = jPatientID.getText();
        String Q10 = jPatientName.getText();
        String Q11 = jBirth.getText();
        String Q12 = jPatientAddres.getText();
        String Q13 = "";
        
        if(jComboTablet.getSelectedItem().equals("Ibuprofeno")){
            Q13 = "Ibuprofeno";
        } else if(jComboTablet.getSelectedItem().equals("Parecetamol")){
            Q13 = "Parecetamol";
        } else if(jComboTablet.getSelectedItem().equals("Dopamina")){
            Q13 = "Dopamina";
        } else if(jComboTablet.getSelectedItem().equals("Morfin")){
            Q13 = "Morfin";
        }
        
        jtxtPrescription.setText("");
        
        jtxtPrescription.append("\t\n\t Hospital Managment System \n"
        + "\nPatient ID:\t\t" + Q9
        + "\nPatient Name:\t\t" + Q10
        + "\nDate Of Birth:\t\t"+ Q11
        + "\nPatient Address:\t" + Q12
        + "\nPrescription:\t\t" + Q13
        + "\nReference Num:\t" + Q1
        + "\nDoze (Mg):\t\t" + Q2 
        + "\nNumber of Tablets:\t" + Q4
        + "\nLOT:\t\t" + Q3
        + "\nDaily Doze:\t\t" + Q5
        + "\nPossible Side Effect:\t" + Q6
        + "\nFurther Information:\t\t" + Q7
        + "\nHow To Use:\t\t" + Q8
        +"\n\nPatient instruction has been printed."
        );
    }//GEN-LAST:event_jBtnPrescriptionActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
        jRef.setText("");
        jDoze.setText("");
        jNumTablets.setName("");
        jLOT.setText("");
        jExpDate.setText("");
        jIssuedDate.setText("");
        jDailyDose.setText("");          
        jSideEffect.setText("");
        jFurInfo.setText("");
        jStorageAdvice.setText("");
        jMachODrive.setText("");
        jHowto.setText("");
        jPatientID.setText("");
        jPatientName.setText("");
        jBirth.setText("");
        jPatientAddres.setText("");
        jComboTablet.getModel().setSelectedItem("Make a prescription");
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(new Object[]{
            jComboTablet.getSelectedItem().toString(),
            jRef.getText(),
            jDoze.getText(),
            jNumTablets.getText(),
            jLOT.getText(),
            jIssuedDate.getText(),
            jExpDate.getText(),
            jDailyDose.getText(),
            jSideEffect.getText(),
            jFurInfo.getText(),
            jStorageAdvice.getText(),
            jMachODrive.getText(),
            jHowto.getText(),
            jPatientID.getText(),
            jNHSnum.getText(),
            jPatientName.getText(),
            jBirth.getText(),
            jPatientAddres.getText()
        });
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        
        if(jTable.getSelectedRow() == -1){
            if(jTable.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "No data deleted", "Hospital Managment System",JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "No data selected", "Hospital Managment System",JOptionPane.OK_OPTION);
            }
        }else {
            model.removeRow(jTable.getSelectedRow());
        }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JTextField jBirth;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JButton jBtnPrescription;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox<String> jComboTablet;
    private javax.swing.JTextField jDailyDose;
    private javax.swing.JTextField jDoze;
    private javax.swing.JTextField jExpDate;
    private javax.swing.JTextField jFurInfo;
    private javax.swing.JTextField jHowto;
    private javax.swing.JTextField jIssuedDate;
    private javax.swing.JTextField jLOT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMachODrive;
    private javax.swing.JTextField jNHSnum;
    private javax.swing.JTextField jNumTablets;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jPatientAddres;
    private javax.swing.JTextField jPatientID;
    private javax.swing.JTextField jPatientName;
    private javax.swing.JTextField jRef;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jSideEffect;
    private javax.swing.JTextField jStorageAdvice;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jtxtPrescription;
    // End of variables declaration//GEN-END:variables
}
